# Change these first
owner: hentaiOS-Infrastructure # Your GitHub organization or username, where this repository lives
repo: infra-status-upptime # The name of this repository

sites:
  - name: hentaiOS Download Page
    url: https://downloads.hentaios.com
  - name: hentaiOS Blog
    url: https://blog.hentaios.com
  - name: hentaiOS Wiki
    url: https://wiki.newcentrix.helluvaos.com
  - name: hentaiOS Forum
    url: https://forum.helluvaos.com
  - name: hentaiOS Mail
    url: https://mail.hentaios.com
  - name: hentaiOS GitLab
    url: https://gitlab.hentaios.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hentaios.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/hentaiOS-Infrastructure/infra-status-upptime/master/assets/status.svg
  name: hentaiOS Status
  hideNavTitle: true
  introTitle: "**hentaiOS Status** is status page of hentaiOS Service and Daemons."
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/hentaiOS-Infrastructure/infra-status-upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/hentaiOS

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
